Resources:
  ServerlessAppRunnerAppRunner:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: serverless-app-runner-${sls:stage}
      SourceConfiguration:
        ImageRepository:
          ImageIdentifier: ${aws:accountId}.dkr.ecr.${aws:region}.amazonaws.com/serverless-app-runner-${sls:stage}:latest
          ImageRepositoryType: ECR
          ImageConfiguration:
            RuntimeEnvironmentVariables:
              - Name: STAGE
                Value: ${sls:stage}
              - Name: ENVIRONMENT
                Value: production
            Port: 8080
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt ServerlessAppRunnerAccessRole.Arn
      InstanceConfiguration:
        Cpu: '1 vCPU'
        Memory: '2 GB'
        InstanceRoleArn: !GetAtt ServerlessAppRunnerInstanceRole.Arn
      HealthCheckConfiguration:
        HealthyThreshold: 2
        Interval: 5
        Path: /
        Protocol: HTTP
        Timeout: 4
        UnhealthyThreshold: 2